import { Theme } from "./type";

const everforestDarkTheme: Theme = {
  "--background": "#272e33",
  "--text-color": "#d3c6aa",
  "--link-hover": "#8ec07c",
  "--link-color": "#4c9173",
  "--li-marker": "#c37272",
  "--home-next-steps-background": "#282828",
  "--code-background": "#4d4d4d4d",
  "--view-all-background": "#3c3836",
  "--view-all-background-hover": "#3c3836",
  "--projects-paragraph": "#919191",
  "--project-box-background": "#282828",
  "--books-paragraph": "#919191",
  "--blog-reading-time": "gray",
  "--blog-no-of-blogs": "#919191",
  "--blog-container-hover": "#282828",
  "--blog-container-focus": "#fbf1c7",
  "--details-background": "#22272a",
  "--details-focus": "#22272a",
  "--summary-color": "#ebdbb2",
  "--summary-list-color": "#7a9f61",
  "--tags-background": "#191919",
  "--tags-color": "#fbf1c7",
  "--tag-selected": "#fff",
  "--tag-selected-background": "#7d5750",
  "--input-container-background": "rgb(34, 34, 34)",
  "--container-svg-color": "gray",
  "--input-color": "white",
  "--other-color": "gray",
  "--next-prev-info-color": "gray",
  "--next-prev-container-hover": "#191919",
  "--blog-container-title": "white",
  "--blog-other-info-color": "gray",
  "--blog-caption": "gray",
  "--blog-caption-link": "white",
  "--blog-content-color": "rgba(255, 255, 255, 0.74)",
  "--blog-text-color": "#ebdbb2",
  "--like-button": "#fff",
  "--like-button-hover": "rgb(199, 73, 73)",
  "--blog-span-info": "#ebdbb2",
  "--blog-information": "red",
  "--blog-headers": "#ebdbb2",
  "--blog-description": "#ebdbb2",
  "--blog-headers-link": "#7a9f61",
  "--blockquote-background": "#282828",
  "--blockquote-color": "white",
  "--header-separator-color": "#b8bb26",
  "--other-separator-color": "#83a598",
  "--callout-icon-green": "#8ec07c",
  "--callout-background-green": "#689d6a",
  "--callout-icon-red": "#cc241d",
  "--callout-background-red": "#fb4934",
  "--callout-color": "black",
  "--card-background": "#282828",
  "--card-border": "#928374",
  "--code-filename-color": "white",
  "--code-filename-container": "#181818",
  "--codeblock-background": "#32302f",
  "--hidden-expand-background": "#2e2e2e63",
  "--hidden-expand-color": "white",
  "--ol-ul-marker": "#c37272",
  "--anchor-color": "#7d5750",
  "--theme-one": "#a7c080",
  "--theme-two": "#7fbbb3",
  "--theme-three": "#83c092",
  "--theme-four": "#d699b6",
  "--nav-links-color": "#999999",
  "--nav-link-active": "#8ec07c",
  "--nav-link-container-color": "#8ec07c",
  "--kbar-click": "#fff",
  "--kbar-command": "#fff",
  "--footer-border-top": "rgb(27, 27, 27)",
  "--footer-color": "gray",
  "--footer-color-hover": "#b8bb26",
  "--users-online-circle": "#7a9f61",
  "--spotify-container-background": "rgba(0, 0, 0, 0.2)",
  "--spotify-container-hover": "rgba(0, 0, 0, 0.324)",
  "--spotify-title": "white",
  "--command-bar-shadow": "#1e2326cf",
  "--command-bar-animator-background": "#121212",
  "--command-bar-color": "#fff",
  "--command-bar-search-background": "#121212",
  "--command-bar-result-background": "#83c092",
  "--code-text": "#d4d4d4",
  "--code-bg": "#1e1e1e",
  "--code-selection-bg": "#264f78",
  "--comment-color": "#6a9955",
  "--string-color": "#ce9178",
  "--number-color": "#b5cea8",
  "--keyword-color": "#569cd6",
  "--keyword-control-color": "#c586c0",
  "--function-color": "#dcdcaa",
  "--class-color": "#4ec9b0",
  "--variable-color": "#9cdcfe",
  "--punctuation-color": "#d4d4d4",
  "--tag-color": "#569cd6",
  "--tag-punctuation": "#808080",
  "--attr-name-color": "#9cdcfe",
  "--attr-value-color": "#ce9178",
  "--regex-color": "#d16969",
  "--highlight-bg": "rgba(55, 65, 81, 0.5)",
  "--highlight-border": "rgb(59, 130, 246)",
  "--line-number-color": "rgb(107, 107, 107)",
  "--inserted-line-bg": "rgba(16, 185, 129, 0.2)",
  "--deleted-line-bg": "rgba(239, 68, 68, 0.2)",
  "--global-font": "Overpass Mono",
  "--code-font": "Overpass Mono",
};

export default everforestDarkTheme;
