import { Theme } from "./type";

const rosepineDarkTheme: Theme = {
  "--background": "#191724",
  "--text-color": "#e0def4",
  "--link-hover": "#9ccfd8",
  "--link-color": "#31748f",
  "--li-marker": "#eb6f92",
  "--home-next-steps-background": "#1f1d2e",
  "--code-background": "#26233a4d",
  "--view-all-background": "#26233a",
  "--view-all-background-hover": "#26233a",
  "--projects-paragraph": "#908caa",
  "--project-box-background": "#1f1d2e",
  "--books-paragraph": "#908caa",
  "--blog-reading-time": "#6e6a86",
  "--blog-no-of-blogs": "#908caa",
  "--blog-container-hover": "#1f1d2e",
  "--blog-container-focus": "#e0def4",
  "--details-background": "#21202e",
  "--details-focus": "#21202e",
  "--summary-color": "#e0def4",
  "--summary-list-color": "#c4a7e7",
  "--tags-background": "#191724",
  "--tags-color": "#e0def4",
  "--tag-selected": "#e0def4",
  "--tag-selected-background": "#eb6f92",
  "--input-container-background": "#1f1d2e",
  "--container-svg-color": "#6e6a86",
  "--input-color": "#e0def4",
  "--other-color": "#6e6a86",
  "--next-prev-info-color": "#6e6a86",
  "--next-prev-container-hover": "#191724",
  "--blog-container-title": "#e0def4",
  "--blog-other-info-color": "#6e6a86",
  "--blog-caption": "#6e6a86",
  "--blog-caption-link": "#e0def4",
  "--blog-content-color": "rgba(224, 222, 244, 0.74)",
  "--blog-text-color": "#e0def4",
  "--like-button": "#e0def4",
  "--like-button-hover": "#eb6f92",
  "--blog-span-info": "#e0def4",
  "--blog-information": "#eb6f92",
  "--blog-headers": "#e0def4",
  "--blog-description": "#e0def4",
  "--blog-headers-link": "#c4a7e7",
  "--blockquote-background": "#1f1d2e",
  "--blockquote-color": "#e0def4",
  "--header-separator-color": "#f6c177",
  "--other-separator-color": "#9ccfd8",
  "--callout-icon-green": "#9ccfd8",
  "--callout-background-green": "#31748f",
  "--callout-icon-red": "#eb6f92",
  "--callout-background-red": "#eb6f92",
  "--callout-color": "#191724",
  "--card-background": "#1f1d2e",
  "--card-border": "#6e6a86",
  "--code-filename-color": "#e0def4",
  "--code-filename-container": "#191724",
  "--codeblock-background": "#26233a",
  "--hidden-expand-background": "#403d5263",
  "--hidden-expand-color": "#e0def4",
  "--ol-ul-marker": "#eb6f92",
  "--anchor-color": "#eb6f92",
  "--theme-one": "#f6c177",
  "--theme-two": "#9ccfd8",
  "--theme-three": "#31748f",
  "--theme-four": "#c4a7e7",
  "--nav-links-color": "#6e6a86",
  "--nav-link-active": "#9ccfd8",
  "--nav-link-container-color": "#9ccfd8",
  "--kbar-click": "#e0def4",
  "--kbar-command": "#e0def4",
  "--footer-border-top": "#21202e",
  "--footer-color": "#6e6a86",
  "--footer-color-hover": "#f6c177",
  "--users-online-circle": "#c4a7e7",
  "--spotify-container-background": "rgba(25, 23, 36, 0.2)",
  "--spotify-container-hover": "rgba(25, 23, 36, 0.324)",
  "--spotify-title": "#e0def4",
  "--command-bar-shadow": "#151422cf",
  "--command-bar-animator-background": "#191724",
  "--command-bar-color": "#e0def4",
  "--command-bar-search-background": "#191724",
  "--command-bar-result-background": "#c4a7e7",
  "--code-text": "#e0def4",
  "--code-bg": "#191724",
  "--code-selection-bg": "#403d52",
  "--comment-color": "#6e6a86",
  "--string-color": "#ebbcba",
  "--number-color": "#f6c177",
  "--keyword-color": "#31748f",
  "--keyword-control-color": "#c4a7e7",
  "--function-color": "#9ccfd8",
  "--class-color": "#9ccfd8",
  "--variable-color": "#e0def4",
  "--punctuation-color": "#908caa",
  "--tag-color": "#31748f",
  "--tag-punctuation": "#6e6a86",
  "--attr-name-color": "#ebbcba",
  "--attr-value-color": "#f6c177",
  "--regex-color": "#eb6f92",
  "--highlight-bg": "rgba(38, 35, 58, 0.5)",
  "--highlight-border": "#c4a7e7",
  "--line-number-color": "#6e6a86",
  "--inserted-line-bg": "rgba(156, 207, 216, 0.2)",
  "--deleted-line-bg": "rgba(235, 111, 146, 0.2)",
  "--global-font": "Miriam Libre",
  "--code-font": "Jetbrains Mono",
};

export default rosepineDarkTheme;
